import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smart Stock",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={montserrat.variable} suppressHydrationWarning>
      <body className="min-h-screen bg-gray-50 text-gray-900">
        <main className="max-w-7xl bg-gray-50 text-gray-900 mx-auto p-6">{children}</main>
      </body>
    </html>
  );
}
